### ISSUE TITLE
feature request: firefox support (firejambo?)

### ISSUE THREAD

**Issue by BoogieHasFun** [LiamHarrison25/Jambofy-Extension#5]
my life without jambo is horrible, this extension would fix my problem but i do not use chrome or chromium based browsers. i would try porting the extension to firefox but i have no understanding of javascript and firefox extension development. so it'd be nice if you made it support firefox by default

**Comment by LiamHarrison25** [comment]
There is a port that was made for Firefox but it was not made by me. Here is the link: https://addons.mozilla.org/en-US/firefox/addon/jambofy/.
